apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world2-deployment
  labels:
    app: helloworld2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld2
  template:
    metadata:
      labels:
        app: helloworld2     
    spec:
      containers:
      - name: helloworld
        image: lorenzobagossi856/helloworld:3
        ports:
        - containerPort: 5000