apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helloworld2
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: lorenzobagossi856/helloworld:~4
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/lorenzoBagossi/HelloWorld2-dev.git
    path: overlays/production
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true